### ISSUE TITLE
Center Example A?

### ISSUE THREAD

**Issue by marcelvoss95** [antennaio/jquery-bar-rating#24]
I am struggeling to center Example A?

Any tips for me?

**Comment by antennaio** [comment]
Hey Marcel,

It's more of a css issue than anything else.

Try:

```css
.rating-a .br-widget {
  margin: auto;
  width: 220px;
  ...
}
```
