### ISSUE TITLE
Vertical bar rating

### ISSUE THREAD

**Issue by dusanvit** [antennaio/jquery-bar-rating#27]
Hello,

would it be possible to add option to rotate Bar Rating vertically? 

Dusan

**Comment by antennaio** [comment]
Hi Dusan 

It's currently possible to have a vertical rating. 

```html
<div class="rating-a">
    <label for="example-a">Vertical example:</label>
    <select id="example-a" name="rating">
        <option value="5">5</option>
        <option value="4">4</option>
        <option value="3">3</option>
        <option value="2">2</option>
        <option value="1" selected="selected">1</option>
    </select>
</div>
```

You will have to `reverse` the ratings, so that the lowest value of a rating is at the bottom and highest value at the top.

```javascript
$('#example-a').barrating('show', {
    reverse: true
});
```

Style the widget without floating `a` elements:

```css
.rating-a .br-widget {
}

.rating-a .br-widget a {
    display: block;
    width: 25px;
    height: 25px;
    background-color: #e3e3e3;
    margin: 1px;
}

.rating-a .br-widget a.br-active,
.rating-a .br-widget a.br-selected {
    background-color: #59a6d6;
}
```
